apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp
spec:
  containers:
  - name: webapp-container
    image: 481454206029.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-ecr:WebAPP-20240302001806
    ports:
    - containerPort: 8080
    env:
    - name: DBHOST
      value: "mysql-pod-service.sqldb"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: my-db-credentials
          key: password
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "blue"
  imagePullSecrets:
    - name: my-aws-ecr-cred
