apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /v1/(.*)
        backend:
          service:
            name: webapp-service
            port:
              number: 8080
      - pathType: ImplementationSpecific
        path: /v2/(.*)
        backend:
          service:
            name: webapp2-service
            port:
              number: 8080
