apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
      - name: webapp-container
        image: 481454206029.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment2-ecr:WebAPP-20240302001806
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-pod-service.sqldb"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: my-db-credentials
              key: password
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"
      imagePullSecrets:
      - name: my-aws-ecr-cred

